apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq # has to match .spec.template.metadata.labels
  serviceName: rabbitmq-service
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: rabbitmq # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: rabbitmq
        ports:
        - name: amqp
          containerPort: 5672
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq/
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: standard
      resources:
        requests:
          storage: 1Gi