apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: user-claim0
  name: user-db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
