apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    service: user-service
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      service: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
        - image: krixlion/user-service:latest
          name: user
          ports:
            - containerPort: 50051
              name: grpc
          # resources:
            # requests:
            #   cpu: 200m
            #   memory: 512M
            # limits:
            #   cpu: 1000m
            #   memory: 3Gi
      restartPolicy: Always
