apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: user-claim
  name: user-db-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  reclaimPolicy:
  resources:
    requests:
      storage: 10Gi
