apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: user-read-db-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  reclaimPolicy:
  resources:
    requests:
      storage: 20Gi
