apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    service: user-write-db-service
  name: user-write-db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-write-db-service
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        service: user-write-db-service
    spec:
      containers:
        - image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: admin123
            - name: POSTGRES_USER
              value: admin
          name: user-write-db
          volumeMounts:
            - name: user-write-db-data
              mountPath: /data/db
          ports:
            - containerPort: 27017
          # resources:
            # requests:
            #   cpu: 200m
            #   memory: 512M
            # limits:
            #   cpu: 1000m
            #   memory: 3Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: user-write-db-data
          persistentVolumeClaim:
            claimName: user-write-db-claim
