apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      service: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/user: "true"
        service: user
    spec:
      containers:
        - image: krixlion/user:latest
          name: user
          ports:
            - containerPort: 5011
          resources: 
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200mm
          volumeMounts:
            - mountPath: /app
              name: user-claim0
      restartPolicy: Always
      volumes:
        - name: user-claim0
          persistentVolumeClaim:
            claimName: user-claim0
status: {}
