apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    service: user-service
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      service: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/user: "true"
        service: user
    spec:
      containers:
        - image: krixlion/user-service:latest
          name: user
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: 200m
              memory: 512M
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
