apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: eventstore-service
  name: eventstore
spec:
  replicas: 3
  selector:
    matchLabels:
      service: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: dev
      labels:
        network/eventstore: "true"
        service: eventstore
    spec:
      containers:
        - image: krixlion/eventstore:latest
          name: eventstore
          ports:
            - containerPort: 50011
          resources:
            # requests:
            #   cpu: 200m
            #   memory: 512M
            # limits:
            #   cpu: 1000m
            #   memory: 3Gi
      restartPolicy: Always