apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    service: eventstore-db
  name: eventstore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eventstore-db
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        service: eventstore-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin123
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_DATABASE 
              value: eventstore
          image: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          name: microservices-eventstore-db
          volumeMounts:
            - name: eventstore-db-data
              mountPath: /data/db
          # resources:
            # requests:
            #   cpu: 200m
            #   memory: 512M
            # limits:
            #   cpu: 1000m
            #   memory: 3Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: eventstore-db-data
          persistentVolumeClaim:
            claimName: eventstore-db-claim