apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: eventstore-claim0
  name: eventstore-db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
