apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: eventstore-claim
  name: eventstore-db-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
