apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: eventstore
  name: eventstore
spec:
  replicas: 3
  selector:
    matchLabels:
      service: eventstore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/eventstore: "true"
        service: eventstore
    spec:
      containers:
        - image: krixlion/eventstore:latest
          name: eventstore
          ports:
            - containerPort: 5011
          resources: 
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200mm
          volumeMounts:
            - mountPath: /app
              name: eventstore-claim0
      restartPolicy: Always
      volumes:
        - name: eventstore-claim0
          persistentVolumeClaim:
            claimName: eventstore-claim0
status: {}
