name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD}}
    
    - name: Build the User docker image
      run: docker build ./user --tag ${{ secrets.DOCKER_USER }}/user-service
      
    - name: Build the Eventstore docker image
      run: docker build ./eventstore --tag ${{ secrets.DOCKER_USER }}/eventstore-service
      
    - name: Build the fluentd docker image
      run: docker build ./fluentd --tag ${{ secrets.DOCKER_USER }}/fluentd
    
    - name: Docker push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/eventstore-service
        docker push ${{ secrets.DOCKER_USER }}/user-service
        docker push ${{ secrets.DOCKER_USER }}/fluentd
      
