name: Eventstore Docker Image CI
on:
  workflow_dispatch:
  push:
    branches:
    - dev
    paths:
    - 'eventstore/**'
  # pull_request:
  #   paths: 
  #   - 'eventstore/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
      
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
        
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD}}
      

    - name: Build and push eventstore service
      uses: docker/build-push-action@v3
      with:
        context: ./eventstore
        push: true
        tags: ${{ secrets.DOCKER_USER }}/eventstore:latest


