name: Fluentd Docker Image CI
on:
  push:
    paths:
    - 'fluentd/**'
  pull_request:
    paths: 
    - 'fluentd/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD}}
      
    - name: Build and push fluentd 
      uses: docker/build-push-action@v3
      with:
        context: ./fluentd
        push: true
        tags: krixlion/fluentd:latest

      