name: GKE CD dry run
on:
  workflow_dispatch:
  push:
    branches:
      - '!dev'
    paths:
    - 'k8s/**'
  pull_request:
    paths:
    - 'k8s/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: 'Access GKE cluster'
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone europe-central2-a
          
      - name: 'Apply k8s manifests'
        run: |
          kubectl apply -R -f k8s/ --dry-run=client
