name: GKE CD
on:
  push:
    paths:
    - 'k8s/**'
  pull_request:
    paths: 
    - 'k8s/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Apply k8s manifests'
        run: |
          kubectl apply -f k8s/user
          kubectl apply -f k8s/eventstore


