name: GKE CD
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
    - 'k8s/**'
  # pull_request:
  #   paths:
  #   - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: 'Access GKE cluster'
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone europe-central2-a
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        
      - name: 'Apply k8s manifests'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            if [[ $file == *.yaml ]]; then
              kubectl delete -f $file
              kubectl apply -f $file
            fi
          done
          
